# Generated by Django 5.2.15 on 2026-06-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('medicine_name', models.CharField(max_length=100)),
                ('avatar_path', models.CharField(blank=True, max_length=255)),
                ('use_asset', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'medicine_requests',
            },
        ),
    ]
